package other

class ListLengths {
    init {
        val list = listOf(
            """bio""",
            """"Áve María, grátia pléna, Dóminus técum. Benedícta tu in muliéribus, et benedíctus frúctus véntris túi, Iésus..." The prayer, spoken through a throat choked with sorrow, echoes off the walls and off the shelves and shelves of mildewed books and scrolls. The air is thick with the smell of dust and age. The room is alight with the glow of a hundred candles, dancing their slow flickering dance. "...Sáncta María, Máter Déi, óra pro nóbis peccatóribus, nunc et in hóra mórtis nóstrae..." The weeping man kneels, bare-chested, at the foot of a silver chalice, a holy relic. He recites his prayer of penance over and over, his voice shrinking to a hoarsely rasping whisper. His chest is marred with the long crooked lines of a vicious scar, running from neck to abdomen and shoulder to shoulder, the form of a cross. "Áve María, grátia pléna, Dóminus técum. Benedícta tu in muliéribus, et benedíctus frúctus véntris túi, Iésus..." He is haunted by her memory, by the sin of his childhood. His life he gives over in service of the Holy Christ, a payment for his sin... It is not enough, not nearly enough, but it is all he has to give. "...Sáncta María, Máter Déi, óra pro nóbis peccatóribus, nunc et in hóra mórtis nóstrae. Amen." Standing, the warrior slips his arms through his undershirt and pulls a suit of chained-mail on over his head. Over the mail, he dons a bright white tabard marked with a scarlet cross, the symbol of the knights templar. Carefully he takes up the relic and exits the small room through its only entryway. He stands squinting for a moment, giving his eyes time to adjust to the bright sunlight, and then begins to wade through the vast pile of bodies strewn about the courtyard. The bodies are those of the warriors slain at his hands and the hands of his knights, warriors who stood between him and the Chalice of Fortitude, unworthy heathens. "Hail, Sir Dupuis! You have the chalice?" Dupuis holds the chalice up, letting the sun glint of its polished surface and then tucks it away as he mounts up on his steed and rides off. His faithful knights follow after him.""",
            """"Burn all, burn everything. Fire is bright and fire is clean"  In the beginning, during the reign of the Mariedian Empire, Fireborgs, manufactured by the Vulcanmech corporation, were just devices, tools to cleanse contamination with fire.  But then the soulborgs rose to power. Soulborg overlords repurposed the Fireborgs as twisted machines of war, transforming them from servants of the Mariedians into monstrous creatures of fire and violence--the Vulcanmech Incendiborgs. New programming took over, and they were given a new mission: the entire world was contaminated, and it must burn.  The Incendiborgs cleansed the world of Mariedian, burning away the messiness and imperfection of nature. They began to consume all remaining life, burning even the soulborgs around them. As the last forests of Mariedian turned to ash, Alpha Prime was born.  From their position locked in fiery conflict on Alpha Prime, the Incendiborgs were summoned to a new world, a world that technology had barely begun to touch, a world that was vibrant and alive--a world that was a tinderbox waiting for a light.  The Vulcanmech have arrived, and now Valhalla will burn.""",
        )
        val newList = list.map { it.length }
        println(newList.maxOrNull())
    }
}